site_name: HoloX Project Documentation
site_description: Central repository for project documentation, decisions, research, and POCs
repo_url: https://github.com/HoloX-co/project-docs
repo_name: HoloX-co/project-docs
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/README.md
    - Diagrams: architecture/diagrams/
  - Decisions:
    - Overview: decisions/README.md
    - ADR-0001 Documentation Strategy: decisions/ADR-0001-documentation-strategy.md
  - Research:
    - Overview: research/README.md
    - Market Analysis: research/market-analysis/
    - Technology Evaluations: research/technology-evaluations/
  - POCs:
    - Overview: poc/README.md
    - Feature X Prototype: poc/feature-x-prototype/
    - Integration Test Results: poc/integration-test-results/
  - Guides:
    - Overview: guides/README.md
  - Meetings:
    - Overview: meetings/README.md
    - August 2025: meetings/2025-08/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate

plugins:
  - search
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true