name: Deploy Hugo with Hextra to GitHub Pages

on:
  push:
    branches: 
      - main
      - 'release/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Node dependencies
        run: npm install
        
      - name: Initialize Hugo module only if missing
        run: |
          if [ ! -f go.mod ]; then
            hugo mod init github.com/HoloX-co/project-docs
          fi
        
      - name: Get Hugo modules
        run: hugo mod get github.com/imfing/hextra
        
      - name: Tidy Hugo modules
        run: hugo mod tidy
        
      - name: Build site
        run: |
          hugo --minify
          npx -y pagefind --site public
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
